@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMTdjMDlkOWFkN2U1YzQyODUxODgwMSIsImlhdCI6MTc4MDAwOTg5OSwiZXhwIjoxNzgyNjAxODk5fQ.FLm4pyU_Gmq8uuWPPJuySeFW-yRfsJ31sasXPhI8eJo

### Health Check
GET http://localhost:3001/api/health

### Register User
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "name": "Albert Camus",
  "username": "acamus2026",
  "email": "sisyphus@uphill-struggles.com",
  "password": "password11x"
}

### Login User
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "narcissus@goldmund.com",
  "password": "password888"
}

### Get All Projects
GET http://localhost:3001/api/projects
Authorization: Bearer {{token}}

### Create Project
POST http://localhost:3001/api/projects
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "MicroCell Hardware",
  "description": "Portable micro-battery unit with embedded display and call routing"
}

### Get Single Project
GET http://localhost:3001/api/projects/6a18d3514e26b7c194eb6205
Authorization: Bearer {{token}}

### Update Project
PUT http://localhost:3001/api/projects/6a18d3514e26b7c194eb6205
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "MicroCell Hardware",
  "description": "Portable micro-battery unit with embedded display, call routing, and thermal management",
  "status": "active"
}

### Delete Project
DELETE http://localhost:3001/api/projects/6a18d3514e26b7c194eb6205
Authorization: Bearer {{token}}

### Get All Tasks
GET http://localhost:3001/api/projects/6a18dac62fb55c8c2c10f280/tasks
Authorization: Bearer {{token}}

### Get Single Task
GET http://localhost:3001/api/projects/6a18dac62fb55c8c2c10f280/tasks/6a18dee941f867c819d56857
Authorization: Bearer {{token}}

### Create Task
POST http://localhost:3001/api/projects/6a18dac62fb55c8c2c10f280/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Thermal regulation spec",
  "description": "Define safe operating temp range",
  "status": "To Do"
}

### Update Task
PUT http://localhost:3001/api/projects/6a18dac62fb55c8c2c10f280/tasks/6a18dee941f867c819d56857
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Thermal regulation spec",
  "description": "Define safe operating temp range and thermal cutoff thresholds",
  "status": "In Progress"
}