### Health Check
GET http://localhost:3001/api/health

### Register User
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "name": "Albert Camus",
  "username": "acamus2026",
  "email": "sisyphus@uphill-struggles.com",
  "password": "password11x"
}

### Login User
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "narcissus@goldmund.com",
  "password": "password888"
}